export const CORALKM_PROTOCOL_URI = 'https://coralkm.com/coralkm'
export const CORALKM_PROTOCOL_VERSION = '0.1'
export const CORALKM_PROTOCOL_PREFIX = `${CORALKM_PROTOCOL_URI}/${CORALKM_PROTOCOL_VERSION}`
