import { Dimensions, StyleSheet } from 'react-native'
import { palette, radius } from '@/constants/design'

const { height: screenHeight } = Dimensions.get('window')

export const styles = StyleSheet.create({
  safeWrapper: { flex: 1, backgroundColor: 'transparent', paddingTop: 50 },
  container: { flex: 1, backgroundColor: 'transparent' },
  chatContainer: { flex: 1, backgroundColor: 'transparent' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 4,
  },
  headerLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', overflow: 'hidden' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 8, marginLeft: 8 },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1B56781A',
  },
  spinning: { transform: [{ rotate: '360deg' }] },
  userDid: {
    fontSize: 12,
    color: '#666',
    flex: 1,
    maxWidth: 70,
    marginLeft: 8,
    overflow: 'hidden',
  },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(11,58,82,0.45)', justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: palette.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  dataContainerScroll: {
    flexGrow: 1,
    backgroundColor: '#0F172A',
    borderRadius: radius.md,
    padding: 12,
    marginVertical: 12,
    maxHeight: 300,
  },
  dataText: { fontSize: 12, fontFamily: 'Courier New', color: '#E5E7EB' },
  drawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
    height: screenHeight,
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  drawerTitle: { fontSize: 18, fontWeight: '600' },
  tabsList: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingHorizontal: 16,
  },
  tabTrigger: { flex: 1, paddingVertical: 12, justifyContent: 'center', alignItems: 'center' },
  tabTriggerActive: { borderBottomWidth: 2, borderBottomColor: '#1B5678' },
  tabText: { fontSize: 14, color: '#666' },
  tabTextActive: { color: '#1B5678', fontWeight: '600' },
  tabContentScroll: { flex: 1, paddingHorizontal: 16, paddingVertical: 16 },
  infoSection: { marginBottom: 20 },
  infoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoTitle: { fontSize: 14, fontWeight: '600' },
  dataTextLarge: { fontSize: 12, fontFamily: 'Courier New', color: '#333', flexShrink: 1 },
  modalTitle: { fontSize: 18, fontWeight: '700', color: palette.heading, marginBottom: 8 },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
    fontSize: 14,
  },
  modalButtonContainer: { flexDirection: 'row', gap: 12 },
  button: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 13,
    backgroundColor: palette.navy,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonOutline: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#ddd' },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  buttonTextOutline: { color: '#333', fontSize: 14, fontWeight: '600' },
})
