import { Dimensions, StyleSheet } from 'react-native'

const { height: screenHeight } = Dimensions.get('window')

export const styles = StyleSheet.create({
  safeWrapper: { flex: 1, backgroundColor: '#fff', paddingTop: 50 },
  container: { flex: 1, backgroundColor: '#fff' },
  chatContainer: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    backgroundColor: '#fff',
  },
  headerLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', overflow: 'hidden' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 0, marginLeft: 8 },
  headerButton: {
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  spinning: { transform: [{ rotate: '360deg' }] },
  userDid: {
    fontSize: 12,
    color: '#666',
    flex: 1,
    maxWidth: 70,
    marginLeft: 8,
    overflow: 'hidden',
  },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  dataContainerScroll: {
    flexGrow: 1,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 12,
    marginVertical: 12,
    maxHeight: 300,
  },
  dataText: { fontSize: 12, fontFamily: 'Courier New', color: '#333' },
  drawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
    height: screenHeight,
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  drawerTitle: { fontSize: 18, fontWeight: '600' },
  tabsList: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingHorizontal: 16,
  },
  tabTrigger: { flex: 1, paddingVertical: 12, justifyContent: 'center', alignItems: 'center' },
  tabTriggerActive: { borderBottomWidth: 2, borderBottomColor: '#007AFF' },
  tabText: { fontSize: 14, color: '#666' },
  tabTextActive: { color: '#007AFF', fontWeight: '600' },
  tabContentScroll: { flex: 1, paddingHorizontal: 16, paddingVertical: 16 },
  infoSection: { marginBottom: 20 },
  infoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoTitle: { fontSize: 14, fontWeight: '600' },
  dataTextLarge: { fontSize: 12, fontFamily: 'Courier New', color: '#333', flexShrink: 1 },
  modalTitle: { fontSize: 18, fontWeight: '600', marginBottom: 8 },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
    fontSize: 14,
  },
  modalButtonContainer: { flexDirection: 'row', gap: 12 },
  button: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#007AFF',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonOutline: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#ddd' },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  buttonTextOutline: { color: '#333', fontSize: 14, fontWeight: '600' },
})
