import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    position: "absolute",
    zIndex: 10,
    top: 30,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  headerSection: {
    alignItems: "center",
    marginBottom: 24,
  },
  header: {
    color: "#1B5678",
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  subheader: {
    color: "#64748b",
    fontSize: 15,
    textAlign: "center",
    lineHeight: 22,
    maxWidth: 280,
  },
  canvasContainer: {
    alignItems: "center",
    marginBottom: 24,
  },
  box: {
    backgroundColor: "#000000",
    borderRadius: 16,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#1B5678",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 3,
    borderColor: "#1B5678",
  },
  canvasHint: {
    marginTop: 12,
    color: "#05070aff",
    fontSize: 13,
    fontStyle: "italic",
  },
  seedSection: {
    width: "100%",
    marginBottom: 20,
  },
  seedHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  seedLabel: {
    color: "#1B5678",
    fontSize: 16,
    fontWeight: "600",
  },
  copyButton: {
    backgroundColor: "#1B5678",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  copyButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
  seedBox: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#e2e8f0",
    minHeight: 80,
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  seedText: {
    color: "#1e293b",
    fontSize: 13,
    textAlign: "center",
    fontFamily: "monospace",
    fontWeight: "500",
    lineHeight: 20,
  },
  seedSubtext: {
    color: "#14181dff",
    fontSize: 12,
    textAlign: "center",
    marginTop: 8,
    fontFamily: "monospace",
  },
  button: {
    backgroundColor: "#1B5678",
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 12,
    minWidth: 160,
    shadowColor: "#1B5678",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  buttonDisabled: {
    backgroundColor: "#cbd5e1",
    shadowOpacity: 0.1,
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 16,
    letterSpacing: 0.5,
  },
});
